### ISSUE TITLE
The next step: 1.10.2

### ISSUE THREAD

**Issue by 3TUSK** [3TUSK/Temp_LocalizationFile#68]
Something something annoy.
Not quite sure about this move. Whatsoever.
- [X] ~~Extra Utilities 2~~ superseded by #67 #69 #71 #72 and rwtema/ExtraUtilities_Localization#43
- [X] Pam's HarvestCraft.  
  It is finally a thing now. Except the translation of "stock". "Bone soup" is not appropriate because it can also be made from veggies, whereas in real life you do need bone (i.e. meat with bone inside, most times pork or chicken) to prepare stock.
- [X] ~~Magic Bees~~ Pause. Until there is further information.
- [X] ~~Botania~~ superseded by Vazkii/Botania#2154 
- [X] ~~...Plants Mega Packs? That one almost killed me.~~ Now not worth, we can't find latest download now
- [X] [Steve Factory Manager](https://github.com/gigabit101/StevesFactoryManager) superseded by gigabit101/StevesFactoryManager#35
- [X] [Steve Carts](https://github.com/modmuss50/SC2) If I remember correctly, someone already got this covered...
- [X] Blood Magic superseded by WayofTime/BloodMagic#1052
- [X] YUNOMakeGoodMap Superseded by TartaricAcid/Minecraft-Mod-Language-Package#2
- [X] CoFHCore
- [X] Thermal Foundation
- [X] Thermal Expansion
- [X] Thermal Dynamics
- [X] Redstone Arsenal

The following tasks are now considered as abandoned; while I am still going to finish them, yet no ETA will be given:
- [Fruit Phone](https://github.com/elytra/FruitPhone)
- OpenComputer Manual. *Lua experts wanted* (even though I know Lua-how-to)
- TIS-3D
- ~~Migrating binnie out when those hardworking awesome folks are ready. Still need the following to be done:~~ Binnie won't be in 1.10.2.
  - ~~Genetics machine name final set~~
  - ~~Clean up color name~~
  - ~~All flower name translated~~
  - ~~All bee name settled~~
  - ~~All tree name settled~~
  - ~~Core part clean up~~
- Thaumcraft 6 

Bonus:
- [X] ~~[ChinaCraft](https://github.com/3TUSK/ChinaCraft/tree/en-us_correction)~~ superseded by UnknownStudio/ChinaCraft#6
- [X] ~~[Tea, A Story of Leaves](https://github.com/3TUSK/Tea-TheStoryOfALeaf/tree/en_us)~~ superseded by LuoXiao-Wing/Tea-TheStoryOfALeaf#1

~~To be continue.~~ No more. We are going to migrate.

**Comment by 3TUSK** [comment]
Action taken. See `binnie-moveout` branch for progress of binnie.

**Comment by 3TUSK** [comment]
Another action taken. See `exu2` branch for progress of xu2 revision.

**Comment by 3TUSK** [comment]
Action taken: gigabit101/StevesFactoryManager#35

**Comment by liach** [comment]
I wonder if you are interested in this: https://github.com/Nuchaz/BiblioCraft/tree/master/assets/bibliocraft2/lang

**Comment by liach** [comment]
I also wonder if you would like to review or maintain LiteLoader localization. It is from me, since [this commit on LiteLoader](http://develop.liteloader.com/liteloader/LiteLoader/commit/7a0a5ccd8371422e5e6c52878d4b4c108bbde4f0). The current location of the file is [here](http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/main/resources/assets/liteloader/lang/zh_cn.lang); although you can register accounts on that GitLab, but you cannot fork repositories, thus changes in localization had better be done in a temporary repository like this one.

**Comment by liach** [comment]
@3TUSK https://github.com/ReplayMod/ReplayMod

**Comment by 3TUSK** [comment]
*sigh* ___overwhelming..___

**Comment by 3TUSK** [comment]
This issue will be closed so long as I finished the ~~Anglicization~~ English translation of _Tea, a Story of Leaves_.

**Comment by 3TUSK** [comment]
LuoXiao-Wing/Tea-TheStoryOfALeaf#1
